import { CalendarClock, CircleDollarSign, History, RotateCcw } from "lucide-react";
import { SubmitButton } from "@/components/admin/submit-button";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { formatBookingVnd } from "@/features/bookings/policy";
import { cancelCheckoutDraftAction, createCheckoutDraftAction, requoteBookingAction, setDepositPolicyAction } from "@/features/checkout/actions";
import { CHECKOUT_BLOCKER_LABELS, CHECKOUT_READINESS_LABELS } from "@/features/checkout/policy";
import type { AdminCheckoutBundle } from "@/features/checkout/types";

function formattedDate(value: string | null) {
  return value ? new Intl.DateTimeFormat("vi-VN", { dateStyle: "short", timeStyle: "short" }).format(new Date(value)) : "—";
}

function localInput(value: string | null) {
  if (!value) return "";
  const date = new Date(value);
  const local = new Date(date.getTime() - date.getTimezoneOffset() * 60_000);
  return local.toISOString().slice(0, 16);
}

export function BookingCheckoutOperations({ bookingId, userRole, checkout }: { bookingId: string; userRole: "admin" | "staff"; checkout: AdminCheckoutBundle }) {
  const { readiness } = checkout;
  const currentPolicy = checkout.policies.find((item) => item.is_current) ?? null;
  const activeSession = checkout.sessions.find((item) => ["draft", "ready"].includes(item.status)) ?? null;
  return <section aria-labelledby="checkout-operations-heading">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 id="checkout-operations-heading" className="text-2xl font-bold text-pine">Sẵn sàng thanh toán</h2><p className="mt-1 text-sm text-muted">Tách biệt với vòng đời Booking và xác nhận nhà cung cấp.</p></div><Badge>{CHECKOUT_READINESS_LABELS[readiness.readiness_state]}</Badge></div>
    <div className="mt-4 grid gap-4">
      <Card className="p-5"><div className="grid gap-3 sm:grid-cols-3"><div><p className="text-xs font-bold uppercase text-muted">Tổng giá trị</p><p className="mt-1 text-xl font-bold text-pine">{readiness.amounts.booking_total_vnd === null ? "Chưa có" : formatBookingVnd(readiness.amounts.booking_total_vnd)}</p></div><div><p className="text-xs font-bold uppercase text-muted">Cần thanh toán trước</p><p className="mt-1 text-xl font-bold text-pine">{readiness.amounts.deposit_due_vnd === null ? "Chưa có" : formatBookingVnd(readiness.amounts.deposit_due_vnd)}</p></div><div><p className="text-xs font-bold uppercase text-muted">Còn lại dự kiến</p><p className="mt-1 text-xl font-bold text-pine">{readiness.amounts.planned_remaining_balance_vnd === null ? "Chưa có" : formatBookingVnd(readiness.amounts.planned_remaining_balance_vnd)}</p></div></div>{readiness.blockers.length ? <ul className="mt-5 grid gap-2 rounded-2xl bg-amber-50 p-4 text-sm leading-6">{readiness.blockers.map((blocker) => <li key={blocker}>• {CHECKOUT_BLOCKER_LABELS[blocker] ?? blocker}</li>)}</ul> : <p className="mt-5 rounded-2xl bg-emerald-50 p-4 text-sm font-bold text-success">Mọi điều kiện hiện tại đã đạt. Provider vẫn chưa được cấu hình.</p>}</Card>
      <div className="grid gap-4 xl:grid-cols-2">
        <Card className="p-5"><h3 className="flex items-center gap-2 font-bold text-pine"><RotateCcw size={18} />Tạo lại báo giá</h3><p className="mt-2 text-sm leading-6 text-muted">Đọc lại nguồn giá/tình trạng trên server, tạo phiên bản mới và vô hiệu phiên checkout cũ.</p><form action={requoteBookingAction} className="mt-4 grid gap-3"><input type="hidden" name="booking_id" value={bookingId} /><Textarea name="reason" required maxLength={500} placeholder="Lý do tạo lại báo giá" /><SubmitButton label="Tạo lại báo giá" confirmation="Tạo phiên bản báo giá mới và làm hết hiệu lực phiên checkout cũ?" /></form></Card>
        <Card className="p-5"><h3 className="flex items-center gap-2 font-bold text-pine"><CircleDollarSign size={18} />Chính sách thanh toán trước</h3>{userRole === "admin" ? <form action={setDepositPolicyAction} className="mt-4 grid gap-3"><input type="hidden" name="booking_id" value={bookingId} /><label className="grid gap-1 text-sm font-bold">Loại chính sách<Select name="policy_type" defaultValue={currentPolicy?.policy_type ?? "manual"}><option value="none">Không cần thanh toán trước</option><option value="fixed_amount">Số tiền cố định</option><option value="percentage">Tỷ lệ phần trăm</option><option value="full_payment">Toàn bộ giá trị</option><option value="manual">Xác định thủ công</option></Select></label><label className="grid gap-1 text-sm font-bold">Số tiền cố định (VND)<Input name="fixed_amount_vnd" type="number" min={0} step={1} defaultValue={currentPolicy?.fixed_amount_vnd ?? ""} /></label><label className="grid gap-1 text-sm font-bold">Tỷ lệ basis points (2500 = 25%)<Input name="percentage_bps" type="number" min={1} max={10000} step={1} defaultValue={currentPolicy?.percentage_bps ?? ""} /></label><div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-sm font-bold">Hủy miễn phí đến<Input name="free_cancel_until" type="datetime-local" defaultValue={localInput(currentPolicy?.free_cancel_until ?? null)} /></label><label className="grid gap-1 text-sm font-bold">Không hoàn lại sau<Input name="non_refundable_after" type="datetime-local" defaultValue={localInput(currentPolicy?.non_refundable_after ?? null)} /></label></div><Textarea name="manual_policy" maxLength={5000} defaultValue={currentPolicy?.manual_policy ?? ""} placeholder="Mô tả chính sách thủ công nếu có" /><Textarea name="cancellation_terms" maxLength={10000} defaultValue={currentPolicy?.cancellation_terms ?? ""} placeholder="Điều khoản hủy khách đã được xem" /><SubmitButton label="Lưu phiên bản chính sách mới" confirmation="Lưu policy mới sẽ hủy phiên checkout đang hoạt động." /></form> : <p className="mt-4 rounded-2xl bg-mist p-4 text-sm leading-6 text-muted">Staff có thể xem nhưng chỉ Admin được tạo phiên bản deposit/cancellation policy mới.</p>}</Card>
      </div>
      <Card className="p-5"><h3 className="flex items-center gap-2 font-bold text-pine"><CalendarClock size={18} />Checkout session</h3>{activeSession ? <div className="mt-4 rounded-2xl border border-line p-4"><div className="flex flex-wrap gap-2"><Badge>{activeSession.status}</Badge><Badge className="bg-mist text-pine">Quote v{activeSession.quote_version}</Badge></div><p className="mt-3 text-sm">Số tiền: <strong>{formatBookingVnd(activeSession.amount_due_vnd)}</strong></p><p className="mt-1 text-sm text-muted">Hết hiệu lực: {formattedDate(activeSession.expires_at)}</p><p className="mt-1 text-sm text-muted">Provider: chưa cấu hình</p><form action={cancelCheckoutDraftAction} className="mt-4 grid gap-3 sm:grid-cols-[1fr_auto]"><input type="hidden" name="booking_id" value={bookingId} /><input type="hidden" name="checkout_session_id" value={activeSession.checkout_session_id} /><Input name="reason" maxLength={500} placeholder="Lý do hủy phiên" /><SubmitButton label="Hủy checkout draft" confirmation="Hủy phiên checkout đang hoạt động?" /></form></div> : <form action={createCheckoutDraftAction} className="mt-4"><input type="hidden" name="booking_id" value={bookingId} /><SubmitButton label="Tạo checkout draft" confirmation="Tạo phiên checkout gắn với quote/policy hiện tại?" /></form>}<p className="mt-3 text-xs leading-5 text-muted">Phiên này không phải giao dịch, không có QR/link thanh toán và không thể đánh dấu đã trả tiền.</p></Card>
      <Card className="p-5"><h3 className="flex items-center gap-2 font-bold text-pine"><History size={18} />Lịch sử báo giá</h3><div className="mt-4 grid gap-3">{checkout.quotes.map((quote) => <div key={quote.id} className="rounded-2xl border border-line p-4"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-bold text-pine">Phiên bản {quote.quote_version}</p><div className="flex gap-2"><Badge>{quote.quote_status}</Badge><Badge className="bg-mist text-pine">{quote.price_status}</Badge></div></div><p className="mt-2 text-sm">{quote.booking_total_vnd === null ? "Chưa đủ tổng giá" : formatBookingVnd(quote.booking_total_vnd)}</p><p className="mt-1 text-sm text-muted">{quote.reason}</p><p className="mt-1 text-xs text-muted">Tạo {formattedDate(quote.quoted_at)} · hết hiệu lực {formattedDate(quote.quote_expires_at)}</p></div>)}{!checkout.quotes.length ? <p className="text-sm text-muted">Chưa có báo giá Phase 9.</p> : null}</div></Card>
    </div>
  </section>;
}
