export const PUBLIC_RATE_RULE_QUERY = [
  "rule_id",
  "rate_plan_id",
  "property_id",
  "room_type_id",
  "rate_type",
  "price_vnd",
  "extra_adult_vnd",
  "extra_child_vnd",
  "rule_valid_from",
  "rule_valid_until",
  "days_of_week",
  "rule_priority",
  "plan_priority",
  "source",
  "price_verified_at",
  "price_valid_until",
  "plan_valid_from",
  "plan_valid_until",
].join(",");

export const ADMIN_RATE_PLAN_QUERY = [
  "id",
  "property_id",
  "code",
  "name",
  "description",
  "currency",
  "valid_from",
  "valid_until",
  "priority",
  "is_active",
  "publish_status",
  "created_at",
  "updated_at",
].join(",");

export const ADMIN_RATE_RULE_QUERY = [
  "id",
  "rate_plan_id",
  "room_type_id",
  "rate_type",
  "price_vnd",
  "extra_adult_vnd",
  "extra_child_vnd",
  "valid_from",
  "valid_until",
  "days_of_week",
  "priority",
  "source",
  "price_verified_at",
  "price_valid_until",
  "is_active",
  "internal_notes",
  "created_at",
  "updated_at",
].join(",");
