export const ROOM_QUALITY_QUERY = [
  "verification_record_id",
  "room_type_id",
  "physical_room_id",
  "cleanliness_score",
  "soundproof_score",
  "heating_score",
  "hot_water_score",
  "wifi_score",
  "bathroom_score",
  "room_accuracy_score",
  "comfort_score",
  "notes_public",
  "notes_internal",
  "created_at",
  "updated_at",
].join(",");

export const PUBLIC_ROOM_QUALITY_QUERY = [
  "verification_record_id",
  "room_type_id",
  "physical_room_id",
  "cleanliness_score",
  "soundproof_score",
  "heating_score",
  "hot_water_score",
  "wifi_score",
  "bathroom_score",
  "room_accuracy_score",
  "comfort_score",
  "notes_public",
  "verified_at",
  "expires_at",
  "verification_state",
  "cleanliness_state",
  "soundproof_state",
  "heating_state",
  "hot_water_state",
  "wifi_state",
  "bathroom_state",
  "room_accuracy_state",
  "comfort_state",
].join(",");

export const ROOM_PROFILE_NOTE_QUERY = [
  "id",
  "room_type_id",
  "physical_room_id",
  "note_type",
  "category",
  "text",
  "sort_order",
  "is_public",
  "created_at",
  "updated_at",
].join(",");

export const PUBLIC_ROOM_PROFILE_NOTE_QUERY = [
  "id",
  "room_type_id",
  "physical_room_id",
  "note_type",
  "category",
  "text",
  "sort_order",
  "created_at",
  "updated_at",
].join(",");
